name: Build and Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Clang and libc++
        run: |
            sudo apt-get update
            sudo apt-get install -y \
              clang-19 \
              libc++-19-dev \
              libc++abi-19-dev

      - name: Check Compiler
        run: |
          clang++-19 --version
          clang++-19 -std=c++23 -stdlib=libc++ -E -x c++ /dev/null

      - name: Configure
        run: |
          CC=clang-19 \
          CXX="clang++-19" \
          cmake --preset debug-tests

      - name: Build
        run: cmake --build --preset debug-tests

      - name: Run Unit Tests
        run: ctest --preset debug-tests --output-on-failure

      - name: Check Application Number
        run: |
          ./_build-ci-release/apps/app -v

      - name: Create Package (CPack)
        run: cpack --preset ci-release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SumoKuBot
          path: |
            _build-ci-release/*.tar.gz
            _build-ci-release/*.tar.gz.sha256
          if-no-files-found: warn
