name: Build C++

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Clang and libc++
        run: |
            sudo apt-get update
            sudo apt-get install -y clang libc++-dev libc++abi-dev

      - name: Check compiler
        run: |
          clang++ --version
          clang++ -std=c++23 -stdlib=libc++ -xc++ -E -v /dev/null

      - name: Configure
        run: |
          CC=clang \
          CXX="clang++ -stdlib=libc++" \
          CI_BUILD_NUMBER=${{ github.run_number }} cmake --preset ci-release

      - name: Build
        run: cmake --build --preset ci-release
