name: C++ CI

on:
  pull_request:
    branches: ["main"]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Compiler and Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake

      - name: Configure CMake
        run: cmake -S . -B build --toolchain=./linux-x86_64.toolchain -Wno-dev

      - name: Build / Compile
        run: cmake --build build --config Release --parallel

      - name: Run Executable
        run: ./build/apps/app
